import type { LiveMatchState } from "./overlay-client";

export const DEMO_MATCH_STATE: LiveMatchState = {
  match_id: "test",
  title: "Premier League 2026 - Grand Final",
  status: "live",
  match_format: "T20",
  overs_per_innings: 20,
  venue: "Lord's Cricket Ground, London",
  current_innings: 2,
  current_over: 18,
  current_ball: 4,
  result_type: null,
  result_description: null,
  team1_name: "Royal Challengers",
  team1_short_name: "RCB",
  team2_name: "Super Kings",
  team2_short_name: "CSK",
  winning_team_name: null,
  innings_number: 2,
  total_runs: 168,
  total_wickets: 5,
  total_overs: 18,
  total_balls: 112,
  extras_total: 8,
  innings_completed: false,
  target_runs: 185,
  batting_team_name: "Royal Challengers",
  batting_team_short_name: "RCB",
  bowling_team_name: "Super Kings",
  bowling_team_short_name: "CSK",
  striker_name: "Virat Kohli",
  striker_runs: 78,
  striker_balls: 46,
  non_striker_name: "Glenn Maxwell",
  non_striker_runs: 34,
  non_striker_balls: 19,
  current_bowler_name: "Ravindra Jadeja",
  bowler_balls: 22,
  bowler_runs: 28,
  bowler_wickets: 2,
  partnership_runs: 52,
  partnership_balls: 31,
  this_over_balls: "1 4 0 6 2",
  current_run_rate: 9.0,
  runs_needed: 17,
  balls_remaining: 8,
  required_run_rate: 12.75,
};
