import type { LiveMatchState } from "~/components/overlay/types";
import type { Match } from "~/lib/match-types";

export const DEMO_MATCH_STATE: LiveMatchState = {
  match_id: "test",
  title: "Premier League 2026 - Grand Final",
  tournament_name: "Premier League 2026",
  status: "live",
  match_format: "T20",
  overs_per_innings: 20,
  venue: "Lord's Cricket Ground, London",
  current_innings: 2,
  current_over: 18,
  current_ball: 4,
  result_type: null,
  result_description: null,
  toss_winner_team_id: "team-rcb",
  toss_decision: "bat",
  umpire1_name: "Richard Kettleborough",
  umpire2_name: "Nitin Menon",
  team1_name: "Royal Challengers",
  team1_short_name: "RCB",
  team1_logo_url: null,
  team2_name: "Super Kings",
  team2_short_name: "CSK",
  team2_logo_url: null,
  winning_team_name: null,
  innings_number: 2,
  total_runs: 168,
  total_wickets: 5,
  total_overs: 18,
  total_balls: 112,
  extras_total: 8,
  innings_completed: false,
  target_runs: 185,
  batting_team_name: "Royal Challengers",
  batting_team_short_name: "RCB",
  bowling_team_name: "Super Kings",
  bowling_team_short_name: "CSK",
  striker_name: "Virat Kohli",
  striker_runs: 78,
  striker_balls: 46,
  non_striker_name: "Glenn Maxwell",
  non_striker_runs: 34,
  non_striker_balls: 19,
  current_bowler_name: "Ravindra Jadeja",
  bowler_balls: 22,
  bowler_runs: 28,
  bowler_wickets: 2,
  partnership_runs: 52,
  partnership_balls: 31,
  this_over_balls: "1 4 0 6 2",
  current_run_rate: 9.0,
  runs_needed: 17,
  balls_remaining: 8,
  required_run_rate: 12.75,
  last_ball_runs: 2,
  last_ball_extras: 0,
  last_ball_extra_type: null,
  last_ball_is_wicket: false,
  last_ball_dismissal_type: null,
  last_ball_dismissed_player: null,
  last_ball_fielder: null,
  last_ball_commentary: "Pushed into deep midwicket for a sharp brace.",
  last_ball_seq: 112,
};

export const DEMO_MATCH_DETAILS: Match = {
  id: "test",
  title: "Premier League 2026 - Grand Final",
  match_format: "T20",
  overs_per_innings: 20,
  status: "live",
  current_innings: 2,
  current_over: 18,
  current_ball: 4,
  venue: "Lord's Cricket Ground, London",
  scheduled_at: new Date().toISOString(),
  toss_winner_team_id: "team-csk",
  toss_decision: "bat",
  umpire1_name: "Richard Kettleborough",
  umpire2_name: "Nitin Menon",
  team1_id: "team-rcb",
  team2_id: "team-csk",
  player_of_the_match: {
    id: "user-vk",
    full_name: "Virat Kohli",
  },
  team1: {
    id: "team-rcb",
    name: "Royal Challengers",
    short_name: "RCB",
    team_players: [
      {
        id: "tp-1",
        team_id: "team-rcb",
        user_id: "u1",
        role_in_team: "Captain / Batter",
        user: { id: "u1", full_name: "Virat Kohli" },
      },
      {
        id: "tp-2",
        team_id: "team-rcb",
        user_id: "u2",
        role_in_team: "Opening Batter",
        user: { id: "u2", full_name: "Faf du Plessis" },
      },
      {
        id: "tp-3",
        team_id: "team-rcb",
        user_id: "u3",
        role_in_team: "All-Rounder",
        user: { id: "u3", full_name: "Glenn Maxwell" },
      },
      {
        id: "tp-4",
        team_id: "team-rcb",
        user_id: "u4",
        role_in_team: "Wicketkeeper / Batter",
        user: { id: "u4", full_name: "Dinesh Karthik" },
      },
      {
        id: "tp-5",
        team_id: "team-rcb",
        user_id: "u5",
        role_in_team: "Batter",
        user: { id: "u5", full_name: "Rajat Patidar" },
      },
      {
        id: "tp-6",
        team_id: "team-rcb",
        user_id: "u6",
        role_in_team: "All-Rounder",
        user: { id: "u6", full_name: "Cameron Green" },
      },
      {
        id: "tp-7",
        team_id: "team-rcb",
        user_id: "u7",
        role_in_team: "Fast Bowler",
        user: { id: "u7", full_name: "Mohammed Siraj" },
      },
      {
        id: "tp-8",
        team_id: "team-rcb",
        user_id: "u8",
        role_in_team: "Fast Bowler",
        user: { id: "u8", full_name: "Lockie Ferguson" },
      },
      {
        id: "tp-9",
        team_id: "team-rcb",
        user_id: "u9",
        role_in_team: "Fast Bowler",
        user: { id: "u9", full_name: "Yash Dayal" },
      },
      {
        id: "tp-10",
        team_id: "team-rcb",
        user_id: "u10",
        role_in_team: "Spinner",
        user: { id: "u10", full_name: "Karn Sharma" },
      },
      {
        id: "tp-11",
        team_id: "team-rcb",
        user_id: "u11",
        role_in_team: "All-Rounder",
        user: { id: "u11", full_name: "Swapnil Singh" },
      },
    ],
  },
  team2: {
    id: "team-csk",
    name: "Super Kings",
    short_name: "CSK",
    team_players: [
      {
        id: "tp-21",
        team_id: "team-csk",
        user_id: "u21",
        role_in_team: "Captain / Batter",
        user: { id: "u21", full_name: "Ruturaj Gaikwad" },
      },
      {
        id: "tp-22",
        team_id: "team-csk",
        user_id: "u22",
        role_in_team: "Opening Batter",
        user: { id: "u22", full_name: "Rachin Ravindra" },
      },
      {
        id: "tp-23",
        team_id: "team-csk",
        user_id: "u23",
        role_in_team: "Batter",
        user: { id: "u23", full_name: "Ajinkya Rahane" },
      },
      {
        id: "tp-24",
        team_id: "team-csk",
        user_id: "u24",
        role_in_team: "Batter",
        user: { id: "u24", full_name: "Shivam Dube" },
      },
      {
        id: "tp-25",
        team_id: "team-csk",
        user_id: "u25",
        role_in_team: "All-Rounder",
        user: { id: "u25", full_name: "Ravindra Jadeja" },
      },
      {
        id: "tp-26",
        team_id: "team-csk",
        user_id: "u26",
        role_in_team: "Wicketkeeper / Finisher",
        user: { id: "u26", full_name: "MS Dhoni" },
      },
      {
        id: "tp-27",
        team_id: "team-csk",
        user_id: "u27",
        role_in_team: "All-Rounder",
        user: { id: "u27", full_name: "Moeen Ali" },
      },
      {
        id: "tp-28",
        team_id: "team-csk",
        user_id: "u28",
        role_in_team: "Fast Bowler",
        user: { id: "u28", full_name: "Deepak Chahar" },
      },
      {
        id: "tp-29",
        team_id: "team-csk",
        user_id: "u29",
        role_in_team: "Fast Bowler",
        user: { id: "u29", full_name: "Tushar Deshpande" },
      },
      {
        id: "tp-30",
        team_id: "team-csk",
        user_id: "u30",
        role_in_team: "Fast Bowler",
        user: { id: "u30", full_name: "Matheesha Pathirana" },
      },
      {
        id: "tp-31",
        team_id: "team-csk",
        user_id: "u31",
        role_in_team: "Spinner",
        user: { id: "u31", full_name: "Maheesh Theekshana" },
      },
    ],
  },
  innings: [
    {
      id: "inn-1",
      match_id: "test",
      innings_number: 1,
      team_id: "team-csk",
      total_runs: 184,
      total_wickets: 6,
      total_balls: 120,
      total_overs: 20,
      is_completed: true,
      extras_total: 10,
      extras_byes: 1,
      extras_leg_byes: 2,
      extras_wides: 5,
      extras_no_balls: 2,
      extras_penalties: 0,
      batting_performances: [
        {
          id: "bp-1",
          match_id: "test",
          innings_id: "inn-1",
          user_id: "u21",
          runs_scored: 62,
          balls_faced: 42,
          fours: 7,
          sixes: 2,
          is_out: true,
          dismissal_type: "caught",
          user: { id: "u21", full_name: "Ruturaj Gaikwad" },
        },
        {
          id: "bp-2",
          match_id: "test",
          innings_id: "inn-1",
          user_id: "u22",
          runs_scored: 38,
          balls_faced: 24,
          fours: 4,
          sixes: 2,
          is_out: true,
          dismissal_type: "bowled",
          user: { id: "u22", full_name: "Rachin Ravindra" },
        },
        {
          id: "bp-3",
          match_id: "test",
          innings_id: "inn-1",
          user_id: "u24",
          runs_scored: 44,
          balls_faced: 21,
          fours: 2,
          sixes: 4,
          is_out: true,
          dismissal_type: "caught",
          user: { id: "u24", full_name: "Shivam Dube" },
        },
        {
          id: "bp-4",
          match_id: "test",
          innings_id: "inn-1",
          user_id: "u26",
          runs_scored: 20,
          balls_faced: 8,
          fours: 2,
          sixes: 2,
          is_out: false,
          dismissal_type: null,
          user: { id: "u26", full_name: "MS Dhoni" },
        },
      ],
      bowling_performances: [
        {
          id: "bl-1",
          match_id: "test",
          innings_id: "inn-1",
          user_id: "u7",
          overs_bowled: 4,
          balls_bowled: 24,
          runs_conceded: 35,
          wickets_taken: 2,
          maidens: 0,
          wides: 2,
          no_balls: 1,
          user: { id: "u7", full_name: "Mohammed Siraj" },
        },
        {
          id: "bl-2",
          match_id: "test",
          innings_id: "inn-1",
          user_id: "u9",
          overs_bowled: 4,
          balls_bowled: 24,
          runs_conceded: 42,
          wickets_taken: 2,
          maidens: 0,
          wides: 1,
          no_balls: 0,
          user: { id: "u9", full_name: "Yash Dayal" },
        },
      ],
    },
    {
      id: "inn-2",
      match_id: "test",
      innings_number: 2,
      team_id: "team-rcb",
      total_runs: 168,
      total_wickets: 5,
      total_balls: 112,
      total_overs: 18,
      is_completed: false,
      target_runs: 185,
      extras_total: 8,
      extras_byes: 0,
      extras_leg_byes: 2,
      extras_wides: 5,
      extras_no_balls: 1,
      extras_penalties: 0,
      batting_performances: [
        {
          id: "bp-11",
          match_id: "test",
          innings_id: "inn-2",
          user_id: "u1",
          runs_scored: 78,
          balls_faced: 46,
          fours: 8,
          sixes: 3,
          is_out: false,
          is_current_batsman: true,
          is_striker: true,
          user: { id: "u1", full_name: "Virat Kohli" },
        },
        {
          id: "bp-12",
          match_id: "test",
          innings_id: "inn-2",
          user_id: "u2",
          runs_scored: 24,
          balls_faced: 16,
          fours: 3,
          sixes: 1,
          is_out: true,
          dismissal_type: "caught",
          user: { id: "u2", full_name: "Faf du Plessis" },
        },
        {
          id: "bp-13",
          match_id: "test",
          innings_id: "inn-2",
          user_id: "u3",
          runs_scored: 34,
          balls_faced: 19,
          fours: 2,
          sixes: 2,
          is_out: false,
          is_current_batsman: true,
          is_striker: false,
          user: { id: "u3", full_name: "Glenn Maxwell" },
        },
      ],
      bowling_performances: [
        {
          id: "bl-21",
          match_id: "test",
          innings_id: "inn-2",
          user_id: "u25",
          overs_bowled: 3,
          balls_bowled: 22,
          runs_conceded: 28,
          wickets_taken: 2,
          maidens: 0,
          wides: 1,
          no_balls: 0,
          is_current_bowler: true,
          user: { id: "u25", full_name: "Ravindra Jadeja" },
        },
        {
          id: "bl-22",
          match_id: "test",
          innings_id: "inn-2",
          user_id: "u30",
          overs_bowled: 3,
          balls_bowled: 18,
          runs_conceded: 32,
          wickets_taken: 2,
          maidens: 0,
          wides: 2,
          no_balls: 1,
          user: { id: "u30", full_name: "Matheesha Pathirana" },
        },
      ],
    },
  ],
};
